### ISSUE TITLE
Cannot enter semicolon after bracket in JS

### ISSUE THREAD

**Issue by dannypernik** [myaaghubi/Auto-Semicolon-VSCode#1]
Thank you for this simple tool. One issue: if a curly bracket is at the end of the line, I cannot append a semicolon. When cursor is at the end of the line, nothing happens when pressing `;`. When cursor is at the beginning of the line, cursor correctly jumps to end but does not add semicolon. When cursor is in the middle of line, sometimes semicolon is added in the wrong position.

![Screen Recording 2023-04-20 at 11 29 16 PM](https://user-images.githubusercontent.com/3347095/233541718-1177437b-ee52-4f23-9bd9-74fcd7efdfe2.gif)

**Comment by myaaghubi** [comment]
Thanks for the issue @dannypernik,
- If your line ends to an opening `{` or closing `}` curly bracket, it's gonna just move the cursor to the end of the line without putting the semicolon because for `PHP` we don't need to have the `;` right after a curly bracket. As a **_solution_** if you somehow need to put it you can do it manually, based on your OS just press the `super` / `win` / `cmd` before `;` or use the command pallet `ctrl + shift + p` > `Semicolone Insert`
- If you press the semicolon inside of the curly bracket pair `{ }`, it's gonna put it at the end of the line inside of the `{ }`. 

For the second point, I may put another shortcut to ignore the curly bracket pair, to make putting the semicolon easier! tell me if you have something different in mind

**Comment by myaaghubi** [comment]
Thanks for the issue @dannypernik,
- If your line ends to an opening `{` or closing `}` curly bracket, it's gonna just move the cursor to the end of the line without putting the semicolon because it's not usual to have the `;` right after a curly bracket in PHP. As a **_solution_** if you somehow need to put it right in the place, based on your OS just press the `super` / `win` / `cmd` before `;` or use the command pallet `ctrl + shift + p` > `Semicolone Insert`
- If you press the semicolon inside of the curly bracket pair `{ }`, it's gonna put it at the end of the line inside of the `{ }`. 

For the second point, I may put another shortcut to ignore the curly bracket pair, to make putting the semicolon easier! tell me if you have something different in mind

**Comment by dannypernik** [comment]
I see that php is the priority for you, but your tool is also very handy for JS, which does often put a semicolon after a curly bracket. I see that you have an `unallowedEnd` constant. Could you make this a customizable setting?

cmd + ; is not working for me (on mac). The command pallete option does work, but there's no way I'm relying on that on a regular basis :)

**Comment by myaaghubi** [comment]
- I see `super + ;` bonded to emojis in the Windows version and on Mac it's not working for you, so I changed the shortcut make sure to check out the README.md
- For curly bracket pair, I put a shortcut to move to the end and auto-add the semicolon.
- Now you can put the semicolon after unallowed endings if the cursor is at the end

I may make a customizable setting later too, for now I hope that changes (76df10fd8e3562086504585cfbfa21159977851f) be fine

**Comment by dannypernik** [comment]
Thank you for taking my feedback, I'm happy to see that I can add a semicolon after an `unallowedEnd` character. But shoot, something is now not working for the key feature - adding `;` at the end of the line after pressing `;` once. I have to press it twice to add one semicolon. No bueno. I tried adjusting the keyboard shortcuts to no avail. Unfortunately it means I'm going to reinstall the previous version for the time being.

**Comment by dannypernik** [comment]
As a side note, I realized that semicolons aren't typically included after curly brackets anyway... it was just an unpleasant experience to be unable to put a semicolon at the location of the cursor.  Ideal behavior from my perspective: If cursor is not at end of line when `;` is clicked, move to end of line, adding a semicolon if not after an `unallowedEnd` character. If cursor is at the end of the line when `;` is clicked, add `;` regardless of the previous character. This means that pressing semicolon a 2nd time will always add a semicolon.

**Comment by myaaghubi** [comment]
This is the way it works after `v0.0.7`: clicking on `;`, moves to the end of the line and auto-adds the `;`, for `unallowedEnd` character, auto-add just gonna moves to the end of the line, no semicolon, however If the cursor is at the end of the line pushing `;`  gonna add the semicolon anyway.
I tested the extension in both the `windows` & `linux` versions of the vscode, and recheck it now to make sure it's ok. However don't have access to a `mac` so it's based on your feedback. Is keybinding works properly on your mac? if one more `;` push after `unallowedEnd` character not satisfying then that ability to customize `unallowedEnd` character is essential.

**Comment by dannypernik** [comment]
@myaaghubi unfortunately on mac `v0.0.7`, the semicolon does not auto-add when pressing `;` even when the last character is allowed. A 2nd press is required. See here:

https://user-images.githubusercontent.com/3347095/234092856-35ad3935-805f-4439-814d-aaca236e81b5.mov

**Comment by dannypernik** [comment]
One other use case that is currently working, but you may want to consider – it's good that a semicolon is placed at the cursor when inside a `for` loop. Any change that would break that use case would not be worthwhile. I'd definitely rather have the `for` loop working than the ability to put a semicolon after the end bracket.

> Ideal behavior from my perspective: If cursor is not at end of line when `;` is clicked, move to end of line, adding a semicolon if not after an `unallowedEnd` character. If cursor is at the end of the line when `;` is clicked, add `;` regardless of the previous character. This means that pressing semicolon a 2nd time will always add a semicolon.

Is this behavior possible? If so, customizing `unallowedEnd` would not be necessary.

**Comment by myaaghubi** [comment]
> One other use case that is currently working, but you may want to consider – it's good that a semicolon is placed at the cursor when inside a `for` loop. Any change that would break that use case would not be worthwhile. I'd definitely rather have the `for` loop working than the ability to put a semicolon after the end bracket.
> 
> > Ideal behavior from my perspective: If cursor is not at end of line when `;` is clicked, move to end of line, adding a semicolon if not after an `unallowedEnd` character. If cursor is at the end of the line when `;` is clicked, add `;` regardless of the previous character. This means that pressing semicolon a 2nd time will always add a semicolon.
> 
> Is this behavior possible? If so, customizing `unallowedEnd` would not be necessary.

We already have both:
- Inside the `()` after `for` statement, auto-add not gonna triggered
- If the cursor is placed at the end of the line `;` allowed 

> @myaaghubi unfortunately on mac `v0.0.7`, the semicolon does not auto-add when pressing `;` even when the last character is allowed. A 2nd press is required. See here:
> 
>  Screen.Recording.2023-04-24.at.2.09.06.PM.mov

Fixed b63d0ff08f5daaa948c35b684f0d6ee4e32567c0 `v0.0.8`

**Comment by dannypernik** [comment]
Beautiful! Everything now working optimally on mac. Thank you for your prompt attention.
